# bloom-settings.conf — Calamares sequence for Bloom OS installer
---
modules-search: [ local, @out@/lib/calamares/modules ]

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - users
    - partition
    - summary
  - exec:
    - partition
    - mount
    - bloom-nixos
    - bloom-prefill
    - umount
  - show:
    - finished

branding: default
prompt-install: false
dont-chroot: false
