/**
 * Bridge management handlers for bloom-services.
 * Manages Matrix bridge containers (WhatsApp, Telegram, Signal) via Podman + Quadlet.
 */
import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import { join } from "node:path";
import { run } from "../../lib/exec.js";
import { getQuadletDir } from "../../lib/filesystem.js";
import { loadBridgeCatalog } from "../../lib/services-catalog.js";
import { validateServiceName } from "../../lib/services-validation.js";
import { errorResult } from "../../lib/shared.js";

/** Generate the Quadlet .container unit content for a bridge. */
function bridgeContainerUnit(name: string, image: string, healthPort: number, configDir: string): string {
	return [
		"[Unit]",
		`Description=Bloom Matrix Bridge — ${name}`,
		"After=network-online.target",
		"Wants=network-online.target",
		"",
		"[Container]",
		`Image=${image}`,
		`ContainerName=bloom-bridge-${name}`,
		`Volume=${configDir}:/data:Z`,
		`PublishPort=127.0.0.1:${healthPort}:${healthPort}`,
		"NoNewPrivileges=true",
		"LogDriver=journald",
		"",
		"[Service]",
		"Restart=on-failure",
		"RestartSec=10",
		"TimeoutStartSec=300",
		"",
		"[Install]",
		"WantedBy=default.target",
		"",
	].join("\n");
}

/** Generate a minimal bridge config pointing to Continuwuity on host.containers.internal:6167. */
function bridgeConfigContent(name: string, healthPort: number): string {
	return [
		`# Bloom bridge config for ${name}`,
		"# Generated by bloom-services bridge_create",
		"",
		"[homeserver]",
		`address = "http://host.containers.internal:6167"`,
		`domain = "localhost"`,
		"",
		`[appservice]`,
		`address = "http://localhost:${healthPort}"`,
		`hostname = "0.0.0.0"`,
		`port = ${healthPort}`,
		`database = "sqlite:///data/${name}.db"`,
		"",
		`[bridge]`,
		`command_prefix = "!${name}"`,
		`personal_filtering_spaces = true`,
		"",
	].join("\n");
}

export async function handleBridgeCreate(
	params: {
		name: string;
	},
	repoDir: string,
	signal: AbortSignal | undefined,
) {
	const guard = validateServiceName(params.name);
	if (guard) return errorResult(guard);

	const catalog = loadBridgeCatalog(repoDir);
	const entry = catalog[params.name];
	if (!entry) {
		const available = Object.keys(catalog).join(", ") || "(none)";
		return errorResult(`Unknown bridge: "${params.name}". Available: ${available}`);
	}

	const { image, health_port } = entry;

	// Pull the bridge image
	const pull = await run("podman", ["pull", image], signal);
	if (pull.exitCode !== 0) {
		return errorResult(`Failed to pull bridge image ${image}:\n${pull.stderr}`);
	}

	// Create config directory
	const configDir = join(os.homedir(), ".config", "bloom", "bridges", params.name);
	mkdirSync(configDir, { recursive: true });

	// Write bridge config
	const configPath = join(configDir, "config.toml");
	if (!existsSync(configPath)) {
		writeFileSync(configPath, bridgeConfigContent(params.name, health_port));
	}

	// Write Quadlet container unit
	mkdirSync(getQuadletDir(), { recursive: true });
	const unitPath = join(getQuadletDir(), `bloom-bridge-${params.name}.container`);
	writeFileSync(unitPath, bridgeContainerUnit(params.name, image, health_port, configDir));

	// Reload systemd and start
	const reload = await run("systemctl", ["--user", "daemon-reload"], signal);
	if (reload.exitCode !== 0) {
		return errorResult(`daemon-reload failed:\n${reload.stderr}`);
	}

	const start = await run("systemctl", ["--user", "start", `bloom-bridge-${params.name}.service`], signal);
	if (start.exitCode !== 0) {
		return errorResult(`Failed to start bloom-bridge-${params.name}.service:\n${start.stderr}`);
	}

	return {
		content: [
			{
				type: "text" as const,
				text: [
					`Bridge "${params.name}" created and started.`,
					``,
					`Config: ${configPath}`,
					`Quadlet unit: ${unitPath}`,
					`Health port: ${health_port}`,
					``,
					`Next step: register the appservice with Continuwuity by adding the`,
					`appservice registration YAML to /etc/bloom/appservices/.`,
					`Then reload bloom-matrix: sudo systemctl reload bloom-matrix`,
				].join("\n"),
			},
		],
		details: {
			bridge: params.name,
			image,
			health_port,
			configDir,
			unitPath,
		},
	};
}

export async function handleBridgeRemove(
	params: {
		name: string;
	},
	signal: AbortSignal | undefined,
) {
	const guard = validateServiceName(params.name);
	if (guard) return errorResult(guard);

	const unitPath = join(getQuadletDir(), `bloom-bridge-${params.name}.container`);

	// Stop the service (best-effort — may already be stopped)
	await run("systemctl", ["--user", "stop", `bloom-bridge-${params.name}.service`], signal);

	// Remove the Quadlet unit
	if (existsSync(unitPath)) {
		rmSync(unitPath);
	}

	// Reload systemd so the unit disappears
	const reload = await run("systemctl", ["--user", "daemon-reload"], signal);
	if (reload.exitCode !== 0) {
		return errorResult(`daemon-reload failed after unit removal:\n${reload.stderr}`);
	}

	return {
		content: [
			{
				type: "text" as const,
				text: `Bridge "${params.name}" stopped and removed. Config directory preserved at ~/.config/bloom/bridges/${params.name}/.`,
			},
		],
		details: { bridge: params.name },
	};
}

export async function handleBridgeStatus(signal: AbortSignal | undefined) {
	const ps = await run(
		"podman",
		["ps", "--filter", "name=bloom-bridge-", "--format", "table {{.Names}}\t{{.Status}}\t{{.Image}}"],
		signal,
	);

	const output = ps.stdout.trim() || "No bridge containers running.";

	return {
		content: [{ type: "text" as const, text: output }],
		details: { exitCode: ps.exitCode },
	};
}
