d /run/bloom 0770 root root -
d /var/lib/bloom 0755 root root -
d /var/lib/bloom/media 0755 root root -

# Additional /var content from installed system packages
L /var/lib/unbound/root.key - - - - ../../../etc/unbound/dnssec-root.key
d /var/lib/unbound 0755 unbound unbound -
d /var/lib/geoclue 0755 geoclue geoclue -
d /var/cache/libX11 0755 root root -
d /var/cache/libX11/compose 0755 root root -
