#!/usr/bin/env python3
# bloom_nixos/main.py
# Calamares job module: generates Bloom OS NixOS configuration and runs nixos-install.
# Replaces the standard calamares-nixos-extensions nixos module.
#
# Globals read from libcalamares.globalstorage:
#   rootMountPoint  — target mount point, e.g. "/mnt"
#   locale          — dict with "language" key, e.g. {"language": "en_US.UTF-8"}
#   keyboard        — dict with "layout", "variant", "vconsole" keys
#   timezoneName    — string, e.g. "Europe/London"
#   efiSystemPartition — path, e.g. "/boot"

import subprocess
import os
import libcalamares


def pretty_name():
    return "Installing Bloom OS"


def run():
    gs = libcalamares.globalstorage
    root = gs.value("rootMountPoint") or "/mnt"

    # ── Step 1: Generate hardware-configuration.nix ──────────────────────────
    # Precondition: root is already mounted (exec-phase mount job ran before us).
    libcalamares.utils.debug("bloom_nixos: generating hardware config")
    subprocess.check_output(
        ["pkexec", "nixos-generate-config", "--root", root],
        stderr=subprocess.STDOUT,
    )

    # ── Step 2: Write host-config.nix ────────────────────────────────────────
    locale_data   = gs.value("locale") or {}
    keyboard_data = gs.value("keyboard") or {}
    timezone      = gs.value("timezoneName") or "UTC"
    lang          = locale_data.get("language", "en_US.UTF-8")
    kb_layout     = keyboard_data.get("layout", "us")
    kb_variant    = keyboard_data.get("variant", "")
    vconsole      = keyboard_data.get("vconsole", "us")

    # Detect firmware type: EFI if efiSystemPartition is set
    efi_partition = gs.value("efiSystemPartition")
    if efi_partition:
        bootloader_block = (
            "  boot.loader.systemd-boot.enable = true;\n"
            "  boot.loader.efi.canTouchEfiVariables = true;"
        )
    else:
        bootloader_block = (
            '  boot.loader.grub.enable = true;\n'
            '  boot.loader.grub.device = "nodev";\n'
            '  boot.loader.grub.efiSupport = false;'
        )

    host_config = f"""\
# host-config.nix — machine-specific overrides, generated by Calamares bloom_nixos module.
# Do not edit by hand; re-run the installer to regenerate.
{{ ... }}: {{
{bootloader_block}
  networking.hostName = "bloom";
  time.timeZone = "{timezone}";
  i18n.defaultLocale = "{lang}";
  services.xserver.xkb = {{ layout = "{kb_layout}"; variant = "{kb_variant}"; }};
  console.keyMap = "{vconsole}";
  networking.networkmanager.enable = true;
  # NOTE: users.users.pi is NOT defined here.
  # bloom-shell.nix (included via nixosModules.bloom) owns the pi user definition.
  # Calamares users exec module sets the password via chpasswd (dont_create_user = true).
  system.stateVersion = "25.05";
}}
"""

    nixos_dir = os.path.join(root, "etc", "nixos")
    os.makedirs(nixos_dir, exist_ok=True)
    with open(os.path.join(nixos_dir, "host-config.nix"), "w") as f:
        f.write(host_config)

    # ── Step 3: Write local flake.nix ────────────────────────────────────────
    flake_nix = """\
# /etc/nixos/flake.nix — generated by Calamares bloom_nixos module.
# Use `nixos-rebuild switch --flake /etc/nixos#bloom` to update.
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    bloom.url = "github:alexradunet/piBloom";
    llm-agents-nix = {
      url = "github:numtide/llm-agents.nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, bloom, llm-agents-nix, ... }:
  let
    system = "x86_64-linux";
    pkgs = nixpkgs.legacyPackages.${system};
    piAgent = llm-agents-nix.packages.${system}.pi;
    bloomApp = pkgs.callPackage (bloom + "/core/os/pkgs/bloom-app") { inherit piAgent; };
  in {
    nixosConfigurations.bloom = nixpkgs.lib.nixosSystem {
      inherit system;
      specialArgs = { inherit piAgent bloomApp; };
      modules = [
        ./hardware-configuration.nix
        ./host-config.nix
        bloom.nixosModules.bloom
        bloom.nixosModules.bloom-firstboot
      ];
    };
  };
}
"""

    with open(os.path.join(nixos_dir, "flake.nix"), "w") as f:
        f.write(flake_nix)

    # ── Step 4: Run nixos-install ─────────────────────────────────────────────
    libcalamares.utils.debug("bloom_nixos: running nixos-install")
    result = subprocess.run(
        [
            "pkexec", "nixos-install",
            "--root", root,
            "--no-root-passwd",
            "--flake", root + "/etc/nixos#bloom",
        ],
        capture_output=False,
    )
    if result.returncode != 0:
        return (
            "nixos-install failed",
            "Check the installation log for details. You can retry from the summary page.",
        )

    return None
