#!/usr/bin/env python3
# bloom_nixos/main.py
# Calamares job module: generates Bloom OS NixOS configuration and runs nixos-install.
# Replaces the standard calamares-nixos-extensions nixos module.
#
# Globals read from libcalamares.globalstorage:
#   rootMountPoint     — target mount point, e.g. "/mnt"
#   locale             — dict with "language" key, e.g. {"language": "en_US.UTF-8"}
#   keyboard           — dict with "layout", "variant", "vconsole" keys
#   timezoneName       — string, e.g. "Europe/London"
#   efiSystemPartition — path, e.g. "/boot"

import subprocess
import os
import libcalamares

# Absolute paths — Calamares exec modules may run with a minimal PATH.
NIXOS_GENERATE_CONFIG = "/run/current-system/sw/bin/nixos-generate-config"
NIXOS_INSTALL         = "/run/current-system/sw/bin/nixos-install"


def pretty_name():
    return "Installing Bloom OS"


def run():
    try:
        return _run()
    except Exception as e:
        import traceback
        return ("bloom-nixos module error", traceback.format_exc())


def _normalize_locale(locale: str) -> str:
    """Ensure locale is in the glibc-compatible xx_YY.UTF-8 format.

    Calamares may return bare language codes (e.g. "en") or codes without
    an encoding suffix (e.g. "en_US").  NixOS derives the glibc locale as
    "<defaultLocale>/UTF-8", so "en" → "en/UTF-8" which glibc rejects.
    """
    if not locale:
        return "en_US.UTF-8"
    # Already has encoding (e.g. "en_US.UTF-8") — use as-is.
    if "." in locale:
        return locale
    # Has territory but no encoding (e.g. "en_US") — append ".UTF-8".
    if "_" in locale:
        return locale + ".UTF-8"
    # Bare language code (e.g. "en") — cannot reliably guess territory;
    # fall back to the safe default.
    return "en_US.UTF-8"


def _run():
    gs = libcalamares.globalstorage
    root = gs.value("rootMountPoint") or "/mnt"

    # ── Step 1: Generate hardware-configuration.nix ──────────────────────────
    # Calamares exec modules run as root — no pkexec needed.
    # Precondition: root is already mounted (exec-phase mount job ran before us).
    libcalamares.utils.debug("bloom_nixos: generating hardware config")
    result = subprocess.run(
        [NIXOS_GENERATE_CONFIG, "--root", root],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        return (
            "Hardware detection failed",
            result.stderr or "nixos-generate-config exited with an error.",
        )

    # ── Step 2: Write host-config.nix ────────────────────────────────────────
    # Calamares stores these as plain strings, not dicts.
    # timezone key is "timezone" in Calamares GS (not "timezoneName").
    timezone  = gs.value("timezone")         or gs.value("timezoneName") or "UTC"
    lang      = _normalize_locale(gs.value("locale") or "en_US.UTF-8")
    kb_layout = gs.value("keyboardLayout")   or "us"
    kb_variant = gs.value("keyboardVariant") or ""
    # vconsole keymap may not always be set; fall back to the X layout.
    vconsole  = gs.value("keyboardVConsoleKeymap") or gs.value("keyboardLayout") or "us"

    # Bloom OS requires UEFI. Return an error if EFI partition is not detected.
    efi_partition = gs.value("efiSystemPartition")
    if not efi_partition:
        return (
            "UEFI firmware required",
            "Bloom OS requires a UEFI system. This machine does not appear to have an EFI "
            "system partition. Please ensure your firmware is in UEFI mode (not Legacy/CSM) "
            "and retry the installation.",
        )
    bootloader_block = (
        "  boot.loader.systemd-boot.enable = true;\n"
        "  boot.loader.efi.canTouchEfiVariables = true;"
    )

    host_config = f"""\
# host-config.nix — machine-specific overrides, generated by Calamares bloom_nixos module.
# Do not edit by hand; re-run the installer to regenerate.
{{ ... }}: {{
{bootloader_block}
  networking.hostName = "bloom";
  time.timeZone = "{timezone}";
  i18n.defaultLocale = "{lang}";
  services.xserver.xkb = {{ layout = "{kb_layout}"; variant = "{kb_variant}"; }};
  console.keyMap = "{vconsole}";
  networking.networkmanager.enable = true;
  # NOTE: users.users.pi is NOT defined here.
  # bloom-shell.nix (included via nixosModules.bloom) owns the pi user definition.
  # Calamares users exec module sets the password via chpasswd (dont_create_user = true).
  system.stateVersion = "25.05";
}}
"""

    nixos_dir = os.path.join(root, "etc", "nixos")
    os.makedirs(nixos_dir, exist_ok=True)
    with open(os.path.join(nixos_dir, "host-config.nix"), "w") as f:
        f.write(host_config)

    # ── Step 3: Write flake.nix ───────────────────────────────────────────────
    flake_nix = """\
# /etc/nixos/flake.nix — generated by Calamares bloom_nixos module.
# Use `nixos-rebuild switch --flake /etc/nixos#bloom` to update.
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    bloom.url = "github:alexradunet/piBloom";
    llm-agents-nix = {
      url = "github:numtide/llm-agents.nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, bloom, llm-agents-nix, ... }:
  let
    system = "x86_64-linux";
    pkgs = nixpkgs.legacyPackages.${system};
    piAgent = llm-agents-nix.packages.${system}.pi;
    bloomApp = pkgs.callPackage (bloom + "/core/os/pkgs/bloom-app") { inherit piAgent; };
  in {
    nixosConfigurations.bloom = nixpkgs.lib.nixosSystem {
      inherit system;
      specialArgs = { inherit piAgent bloomApp; };
      modules = [
        ./hardware-configuration.nix
        ./host-config.nix
        bloom.nixosModules.bloom
        bloom.nixosModules.bloom-firstboot
      ];
    };
  };
}
"""

    with open(os.path.join(nixos_dir, "flake.nix"), "w") as f:
        f.write(flake_nix)

    # ── Step 4: Build system closure directly onto the target disk ───────────
    # Two problems to avoid:
    # 1. narHash assertion crash: nixos-install --flake --store <target> uses
    #    a non-standard store URL, making computeStorePath() return a different
    #    hash than what was recorded → Nix assertion fails.
    # 2. RAM space exhaustion: building on the host/live store (tmpfs) runs out
    #    of space for large closures (bloom-app + Rust toolchain etc.).
    #
    # Fix: use --store "local?real-root=<target>&store=/nix/store"
    # • real-root=<target> → packages land on the target disk (40 GB, not RAM)
    # • store=/nix/store   → store path format stays standard, narHash passes
    store_uri = f"local?real-root={root}&store=/nix/store"
    flake_attr = (
        root + "/etc/nixos#nixosConfigurations.bloom.config.system.build.toplevel"
    )
    libcalamares.utils.debug(f"bloom_nixos: building system closure to {store_uri}")
    build = subprocess.run(
        [
            "/run/current-system/sw/bin/nix", "build",
            "--no-link", "--print-out-paths",
            "--store", store_uri,
            "--extra-experimental-features", "nix-command flakes",
            # Disable the build sandbox so Nix doesn't create .drv.chroot
            # directories in the live ISO's tmpfs (/nix/store on the host).
            # The sandbox dirs fill RAM faster than the actual packages,
            # causing "No space left on device" before the build completes.
            # All derivations here come from cache.nixos.org or are tiny
            # text-generation steps, so sandboxing provides no real benefit.
            "--option", "sandbox", "false",
            flake_attr,
        ],
        capture_output=True, text=True,
    )
    libcalamares.utils.debug("bloom_nixos: nix build stdout: " + build.stdout[-2000:])
    libcalamares.utils.debug("bloom_nixos: nix build stderr: " + build.stderr[-2000:])
    if build.returncode != 0:
        detail = (build.stderr or build.stdout or "no output")[-3000:]
        return ("System build failed", detail)

    system = build.stdout.strip().splitlines()[0]
    libcalamares.utils.debug(f"bloom_nixos: system closure: {system}")

    # ── Step 5: Set up bootloader via nixos-install --system ─────────────────
    # The closure is already on the target store; nixos-install --system
    # handles profile registration and bootloader installation.
    libcalamares.utils.debug("bloom_nixos: running nixos-install --system")
    install = subprocess.run(
        [
            NIXOS_INSTALL,
            "--root", root,
            "--no-root-passwd",
            "--system", system,
        ],
        capture_output=True, text=True,
    )
    libcalamares.utils.debug("bloom_nixos: nixos-install stdout: " + install.stdout[-2000:])
    libcalamares.utils.debug("bloom_nixos: nixos-install stderr: " + install.stderr[-2000:])
    if install.returncode != 0:
        detail = (install.stderr or install.stdout or "no output")[-3000:]
        return ("nixos-install failed", detail)

    return None
