name: Check

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  fast-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - run: npm ci
      - run: npm run test:unit
      - run: npm run test:integration
      - run: npm run check
      - run: nix build .#checks.x86_64-linux.config --no-link
